package com.example.performance_management_system.event;

public enum EventType {

    // AUTH
    USER_LOGGED_IN,
    USER_LOGGED_OUT,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,

    // USER
    USER_CREATED,
    USER_UPDATED,
    USER_ACTIVATED,
    USER_DEACTIVATED,
    USER_ROLE_CHANGED,
    USER_DEPARTMENT_CHANGED,
    USER_MANAGER_CHANGED,

    // DEPARTMENT
    DEPARTMENT_CREATED,
    DEPARTMENT_UPDATED,
    DEPARTMENT_HEAD_CHANGED,

    // GOAL
    GOAL_CREATED,
    GOAL_SUBMITTED,
    GOAL_APPROVED,
    GOAL_REJECTED,

    // REVIEW
    SELF_REVIEW_SUBMITTED,
    MANAGER_REVIEW_SUBMITTED,

    // RATING
    RATING_CREATED,
    RATING_SUBMITTED,
    RATING_CALIBRATED,
    RATING_FINALIZED,

    // CYCLES
    REVIEW_CYCLE_CREATED,
    REVIEW_CYCLE_ACTIVATED,
    REVIEW_CYCLE_CLOSED,
    PERFORMANCE_CYCLE_CREATED,
    PERFORMANCE_CYCLE_STARTED,
    PERFORMANCE_CYCLE_CLOSED
}
